### PR TITLE
Lib directories

### PR DESCRIPTION
**Pull request by timoore**
Some changes to install osg2vsg in the lib64 directory on systems that are configured that way. Also, install the OSG plugin in the correct directory.

### CODE REVIEW

**Comment by robertosfield** [comment]
I think it would be better to adopt the vsgMacros.cmake and set things up close to vsgXchange etc.

**Comment by robertosfield** [comment]
@rhabacker has just merged the use of vsgMarcos.cmake so this should address the issue with install location/suffix #71

**Comment by timoore** [comment]
I agree that using vsgMacros.cmake is the right way to solve the lib64 problem. However, With the new commits the plugin is still not installed in the OSG plugins directory. Are you interested in a pull request to solve that?

**Comment by rhabacker** [comment]
Does https://github.com/vsg-dev/osg2vsg/pull/73/commits/196418913ba9026597e6f6b84d377dd096ac39a7  not solve this ?

**Comment by timoore** [comment]
> Does [1964189](https://github.com/vsg-dev/osg2vsg/commit/196418913ba9026597e6f6b84d377dd096ac39a7) not solve this ?

It looks like it does. Sorry, I didn't realize that there was a fix in another pull request.

**Comment by robertosfield** [comment]
#73 is now merged, thanks @rhabacker.

**Pull request closed without merging**
