### PR TITLE
Topic fbx

### PR DESCRIPTION
**Pull request by tomhog**
Pull request to see if you can redirect

### CODE REVIEW

**Comment by vsg-dev** [comment]
I have just checked out the PR.  It fails to build because ShaderUtils.h is not included in the PR, could you add this.

**Comment by tomhog** [comment]
Added, not sure what is going on with VS, did the same thing again.
Excluded it from the source control. Maybe I need to check the .gitignore
but surely that's not blocking .h files. I'll be more wary of it now.

**Comment by vsg-dev** [comment]
I have checked in a fix to the .gitignore - it had include/ in there.  I think this might be an erroneous merge from the original work on vsgFramework.  I'll now have a bash at the merge.

**Comment by vsg-dev** [comment]
I now get a bit further but fail in the cmake .:

-- Failed to find Shaderc

Will have a look at the Find script.

**Pull request closed without merging**
