### PR TITLE
Fix building with MinGW when vsg::Path uses wchar_t

### PR DESCRIPTION
**Pull request by rhabacker**
Fix for vsg-dev/VulkanSceneGraph#649

### CODE REVIEW

**Comment by robertosfield** [comment]
What public std::ifstream constructors does Mingw provide?

**Comment by rhabacker** [comment]
> What public std::ifstream constructors does Mingw provide?
```
/home/xxx/src/osg2vsg-src/src/osg2vsg/OSG.cpp: In member function 'virtual vsg::ref_ptr<vsg::Object> osg2vsg::OSG::read(const vsg::Path&, vsg::ref_ptr<const vsg::Options>) const':
/home/xxx/src/osg2vsg-src/src/osg2vsg/OSG.cpp:106:40: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(vsg::Path&)'
  106 |             std::ifstream fin(foundPath);
      |                                        ^
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/osgDB/fstream:20,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/osgDB/Output:20,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/osgDB/DotOsgWrapper:21,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/osgDB/Registry:26,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/osgDB/ReadFile:24,
                 from /home/xxx/src/osg2vsg-src/src/osg2vsg/OSG.cpp:20:
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:584:9: note: candidate: 'template<class _Path, class _Require> std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const _Path&, std::ios_base::openmode) [with _Require = _Path; _CharT = char; _Traits = std::char_traits<char>]'
  584 |         basic_ifstream(const _Path& __s,
      |         ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:584:9: note:   template argument deduction/substitution failed:
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:583:32: error: 'class vsg::Path' has no member named 'make_preferred'
  583 |       template<typename _Path, typename _Require = _If_fs_path<_Path>>
      |                                ^~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:592:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
  592 |       basic_ifstream(basic_ifstream&& __rhs)
      |       ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:592:39: note:   no known conversion for argument 1 from 'vsg::Path' to 'std::basic_ifstream<char>&&'
  592 |       basic_ifstream(basic_ifstream&& __rhs)
      |                      ~~~~~~~~~~~~~~~~~^~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:567:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const std::string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::ios_base::openmode]'
  567 |       basic_ifstream(const std::string& __s,
      |       ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:567:41: note:   no known conversion for argument 1 from 'vsg::Path' to 'const std::string&' {aka 'const std::__cxx11::basic_string<char>&'}
  567 |       basic_ifstream(const std::string& __s,
      |                      ~~~~~~~~~~~~~~~~~~~^~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:549:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const wchar_t*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
  549 |       basic_ifstream(const wchar_t* __s,
      |       ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:549:37: note:   no known conversion for argument 1 from 'vsg::Path' to 'const wchar_t*'
  549 |       basic_ifstream(const wchar_t* __s,
      |                      ~~~~~~~~~~~~~~~^~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:534:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
  534 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      |       ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:534:34: note:   no known conversion for argument 1 from 'vsg::Path' to 'const char*'
  534 |       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      |                      ~~~~~~~~~~~~^~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:523:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]'
  523 |       basic_ifstream() : __istream_type(), _M_filebuf()
      |       ^~~~~~~~~~~~~~
/usr/lib64/gcc/i686-w64-mingw32/12.2.0/include/c++/fstream:523:7: note:   candidate expects 0 arguments, 1 provided

**Comment by rhabacker** [comment]
This change is made obsolete by applying https://github.com/vsg-dev/VulkanSceneGraph/pull/650.

**Comment by rhabacker** [comment]
https://github.com/vsg-dev/VulkanSceneGraph/pull/650 has been applied, so this pr can be closed

**Pull request closed without merging**
