### PR TITLE
Fixed outdated include statement

### PR DESCRIPTION
**Pull request by olegded**

### CODE REVIEW

**Comment by olegded** [comment]
@robertosfield Robert, second try for today :-)

It compiles fine on Mac, showing some warnings about hidden virtual methods.

Unfortunately, I was not able to create some window yet, even using self-compiled GLFW3 library with enabled Vulkan support (using MoltenVK)

**Comment by robertosfield** [comment]
What were the warnings?

How long have you been attempting the build?

FYI, I'm currently working on basic serialization support that should allow us to drop osg2vsg usage within examples like vsgdraw and vsgcompute.

Another change that @tomhog and myself are revving up for is to implement Windows/X11 native windowing relying relying upon GLFW3.  This would lead to the question about what to do about OSX if you are chomping at the bit to port to OSX.  This has been something on my radar but not till next year, happy to help your work if you want to do it sooner.

**Comment by olegded** [comment]
@robertosfield Here are the warnings:

```bash
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/src/osg2vsg/ImageUtils.cpp:13:
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/include/osg2vsg/ImageUtils.h:16:
In file included from /usr/local/include/osgDB/ReadFile:24:
In file included from /usr/local/include/osgDB/Registry:21:
In file included from /usr/local/include/osg/KdTree:18:
In file included from /usr/local/include/osg/Geometry:17:
In file included from /usr/local/include/osg/Drawable:21:
In file included from /usr/local/include/osg/RenderInfo:18:
In file included from /usr/local/include/osg/View:17:
/usr/local/include/osg/Camera:604:25: warning: 'osg::Camera::DrawCallback::run' hides overloaded virtual function [-Woverloaded-virtual]
            inline void run(osg::RenderInfo& renderInfo) const
                        ^
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/src/osg2vsg/ImageUtils.cpp:13:
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/include/osg2vsg/ImageUtils.h:15:
In file included from /usr/local/include/osg/ImageUtils:19:
In file included from /usr/local/include/osg/Image:23:
In file included from /usr/local/include/osg/StateAttribute:19:
/usr/local/include/osg/Callback:80:22: note: hidden overloaded virtual function 'osg::Callback::run' declared here: different number of parameters (2 vs 1)
        virtual bool run(osg::Object* object, osg::Object* data)


In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/src/osg2vsg/ImageUtils.cpp:13:
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/include/osg2vsg/ImageUtils.h:16:
In file included from /usr/local/include/osgDB/ReadFile:24:
In file included from /usr/local/include/osgDB/Registry:21:
/usr/local/include/osg/KdTree:202:32: warning: 'osg::KdTreeBuilder::clone' hides overloaded virtual function [-Woverloaded-virtual]
        virtual KdTreeBuilder* clone() { return new KdTreeBuilder(*this); }
                               ^
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/src/osg2vsg/ImageUtils.cpp:13:
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/include/osg2vsg/ImageUtils.h:16:
In file included from /usr/local/include/osgDB/ReadFile:24:
In file included from /usr/local/include/osgDB/Registry:21:
In file included from /usr/local/include/osg/KdTree:18:
In file included from /usr/local/include/osg/Geometry:17:
In file included from /usr/local/include/osg/Drawable:21:
In file included from /usr/local/include/osg/RenderInfo:18:
In file included from /usr/local/include/osg/View:17:
In file included from /usr/local/include/osg/Camera:17:
In file included from /usr/local/include/osg/Transform:17:
In file included from /usr/local/include/osg/Group:18:
/usr/local/include/osg/NodeVisitor:111:9: note: hidden overloaded virtual function 'osg::NodeVisitor::clone' declared here: different number of parameters (1 vs 0)
        META_Object(osg, NodeVisitor)
        ^
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/src/osg2vsg/ImageUtils.cpp:13:
In file included from /Users/.../dev/osg-vulkan/osg2vsg/src/include/osg2vsg/ImageUtils.h:15:
In file included from /usr/local/include/osg/ImageUtils:19:
In file included from /usr/local/include/osg/Image:17:
In file included from /usr/local/include/osg/BufferObject:20:
/usr/local/include/osg/Object:49:30: note: expanded from macro 'META_Object'
        virtual osg::Object* clone(const osg::CopyOp& copyop) const { return new name (*this,copyop); } \
```

**Comment by olegded** [comment]
Since I'm doing it in my spare time, not too long... I have tried to use GLFW3.3 installed using `brew` and a self-compiled version. I will try to use latest `LunarG` SDK version with included `MoltenVK`, will tell you if that helps.

The "low level" windowing stuff on Mac would be new to me :-) However, I will see how I could help, maybe just by doing some testing.

**Comment by robertosfield** [comment]
Thanks for the info on the warnings. These are all OSG ones, are likely to
be mostly benign.  We can look at these warnings the next time we go for an
OSG stable release.

Once I've merged the serialization work the OSG dependency take more of
back seat, so for normal usage you won't need to use the OSG/osg2vsg, so
the issue of warnings coming in from the OSG side won't be an issue.

Have you got any sample Vulkan programs working with MoltenVK?

**Comment by olegded** [comment]
Warnings -> sure

"Have you got any sample Vulkan programs working with MoltenVK?" -> yes, from LunarG and MoltenVK repos, for macOS and iOS.

Samples from https://github.com/SaschaWillems/Vulkan start as well.

**Comment by olegded** [comment]
OK, latest update on this one:

- MoltenVK and LunarG SDKs come without static Vulkan libraries, at least I couldn't find them
- GLFW3.3 (latest master) tries to load the `libvulkan.1.dylib` library in `_glfwInitVulkan()` at runtime ->  at least `DYLD_LIBRARY_PATH` should be updated to contain that library
- After successful load, `glfwCreateWindowSurface()` checks the Vulkan extensions (`!_glfw.vk.extensions[0]`) and returns `VK_ERROR_EXTENSION_NOT_PRESENT` since extension array is empty

I have tried to use `libvulkan.1.dylib` from LunarG for both GLFW3 and VSG. However, it fails to create some Vulkan instance in this case.

Using `libMoltenVK.dylib` for GLFW3 failed as well so far since it tries to load `libvulkan.1.dylib`.

It's not yet clear to me how to combine (if at all) `libMoltenVK.dylib` and `libvulkan.1.dylib` in this case.

But... I don't give up yet :-) Things to try out:
- Compile libMoltenVK as a static library and try to use it for GLFW3. There is a config option for this case.
- Update GLFW3 to load `libMoltenVK.dylib` at runtime. Maybe this will help.

**Comment by tomhog** [comment]
Hi guys

So I successfully built and ran vsg/vsgExamples on macOS. If you check the macOS vulkansdk documentation (downloaded from LunarG) there is a getting_started_macos. This mentions a few environment variables you need to setup so that vulkan can run (the demo apps ran fine without these, so perhaps they use static build or they inform vulkan of some of these vaules at run time)

The main ones are the following env vars I added to my .bash_profile

export VULKAN_SDK="/Users/thomashogarth/Documents/VSG/vulkansdk/macOS"
export VK_ICD_FILENAMES="$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json"
export PATH="$VULKAN_SDK:$VULKAN_SDK/bin:$PATH"
export DYLD_LIBRARY_PATH="$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH"

The VK_ICD_FILENAMES was the final key for me, before adding that the vulkan sdk would be found but it would state no vulkan loader was available.

PS
No code changes were required, however only the top left corner of the window was rendered too, I'm assuming due to macOS dpi scaling.

**Comment by vsg-dev** [comment]
Thanks for the details @olegded, and @tomhog just wow, great that you've jumped in and got things running!  I was fully expecting VulkanVK to require mods of the VSG/osg2vsg & vsgExamples.

So does this mean we can add OSX as a supported platform then?  A dedicated section to INSTALL.md will be required to explain the steps required and the above env vars.

**Comment by olegded** [comment]
@tomhog Thanks! I missed the part about `VK_ICD_FILENAMES `, it definitely helps! I can now use the `libMoltenVK.dylib` library for all components.

However, now it fails in `_glfwPlatformCreateWindowSurface` while testing `if (!vkCreateMacOSSurfaceMVK)` (in cocoa_window.m, line 1871). Just curious, which versions of `GLFW3`, `LunarG` and `macOS`  are you using? And which GPU? :-)

**Comment by tomhog** [comment]
@olegded So I'm using

macOS 10.13.5
NVIDIA GeForce GT 750M 2048 MB

I cloned the latest master of GLFW from
https://github.com/glfw/glfw

And downloaded the lastest LunarG VulkanSDK for macOS 1.1.85
https://vulkan.lunarg.com/sdk/home#mac

Also might be worth noting I think xcode ignores/sanitises environment variables if you run from within xcode. For example I just added and the VK_ICD_FILENAMES  environment variable manually to the Run scheme in the GLFW project
https://medium.com/@derrickho_28266/xcode-custom-environment-variables-681b5b8674ec
Now the glfw vlukan example runs from inside xcode, where as before it did not. So try that and also try running the exe manually outside of xcode.

PS
I also copied the vulkan libs folder contents etc into usr/local so xcode could find them without the env vars

**Comment by tomhog** [comment]
Im thinking there must be a way round all this as the prebuilt Vulkan examples that ship with the sdk run fine with no adustments and I think have the libs etc embedded in the .app package.

**Comment by olegded** [comment]
@tomhog @robertosfield ok, here we go :-)
screen shot 2018-11-14 at 15 06 52

I have defined `VK_LAYER_PATH` as well and linked anything against `libvulkan.1.0.xx.dylib` (`libvulkan.1.1.85.dylib`) as described by the [getting started guide, "Frameworks and Header/Libraries" section](https://vulkan.lunarg.com/doc/view/1.0.69.0/mac/getting_started.html).

macOS: 10.13.6
GPU: ATI Radeon
GLFW: cloned from git
Vulkan: LunarG VulkanSDK for macOS 1.1.85

**Comment by olegded** [comment]
Yeah, I think that in the end the install step (and maybe the XCode project setup) need to mirror the structure described by the "Application Bundle Structure" section of the "getting started guide", needs more testing and verification. For now, the readme could be probably just updated to reflect all the findings from this thread.

**Comment by vsg-dev** [comment]
Congrats @olegded, first textured quads working under OSX for the VSG project :-)

I'm afraid we don't yet have anything more exciting to show off yet.  Once I got as far as the above with the VSG's Vulkan integration I moved onto other parts of the VSG project.  I'll be returning to more of the graphics side next month.

FYI, by the end of this week I'm aiming to have basic native file format support so will be able be able to load the demo texture data via it rather than relying upon the OSG/osg2vsg to load texture data. Once we are at this point getting the above result will just require VSG and vsgExamples to be built, no need for OSG/osg2vsg for the basic demos.

**Comment by tomhog** [comment]
@olegded nice work, looks better than mine did. Out of interest are you using any sort of "Retina" display? My vsgdraw just rendered to the top left quarter of the window and I'm assuming it was due to DPI scaling as I'm using a macbook with retina display.

**Comment by olegded** [comment]
Yeah, verified on a built-in display, same as for you :-) The screenshot form above is taken on an attached monitor. However, it has 2560x1440 resolution

**Pull request merged**
